### ISSUE TITLE
Event organizer speech in the beggining

### ISSUE THREAD

**Issue by sam-hosseini** [omidfi/how-to-annoy-a-web-developer#1]

**Comment by albacoretuna** [comment]
Thanks sajjad, I'll revise thag section.

**Comment by albacoretuna** [comment]
@Sajjadhosn I just changed section 6, organizations. I think it sounds better now.

**Comment by Sajjadhosn** [comment]
@omidfi It does indeed sound better. Thanks for taking the time.
